### ISSUE TITLE
City of Munich Logo

### ISSUE THREAD

**Issue by klml** [it-at-m/wjh-rechner#34]
Please add a LHM logo within a top nav bar ( e.g. https://pflege-in-muenchen.de or https://opensource.muenchen.de )

So you could integrate the github link also in this topnav.

**Comment by itgkarl** [comment]
The medium-term plan is to integrate the calculator directly into the muenchen.de site by means of a fragment.
It would therefore not be expedient to integrate a header for the time being.
I will therefore close the issue until another decision is made.
If an integration to muenchen.de is not pursued further, a header would still be a good extension for a uniform look and feel.
